export const productConstants = {
    ALL_PRODUCTS:'ALL_PRODUCTS',
    ADD_TO_CART:'ADD_CART_PRODUCT',
    REMOVE_FROM_CART:'REMOVE_CART_PRODUCT',
    VIEW_PRODUCT:'SHOW_PRODUCT',
    ADD_QUANTITY:'ADD_QUANTITY' ,
    REMOVE_QUANTITY:'REMOVE_QUANTITY'  ,
    CLEAR_CART:'CLEAR_CART' ,
    CHECKOUT:'CHECKOUT',
    PAYMENT_DONE:'PAYMENT_DONE',
    FILTER_PRODUCTS:'FILTER_PRODUCTS',
    SORT_PRODUCTS:'SORT_PRODUCTS'
};